### PR TITLE
Feat/mute 841 vc examples tests

### PR DESCRIPTION
**Pull request by gjgd**
Add tests for vc.transmute.world

### CODE REVIEW

**Comment by OR13** [comment]
@gjgd I'm seeing some failures when I add more credentials, can you add these as well: https://github.com/w3c-ccg/vc-examples/pull/86

**Comment by gjgd** [comment]
Added the credentials and seeing tests failures as well.

One reason I identified was the `verificationMethod` from DanubTech's vc: https://github.com/transmute-industries/vc.transmute.world/blob/3e33d260100ddd0bcadd9757c500cc90a636febc/tests/plugfest-2020/vendors/transmute-local/verifiable_credentials/DanubeTech-PermanentResidentCard.json#L36
It is listed in the `authentication` section of the corresponding did document, and not `assertionMethod`. See: https://resolve.transmute.world/#did:v1:test:nym:z6MktyAYL7sVcmPQPTbbMqrnGMNwp6zkvRvKREs94f81fA1K#z6MkgumSeJ8FGqFjXFPJSsT2EFCNYVvx5RXDQ6oBYDrmtiDb

The `vcjs.verifyCredential` doesn't like that and throws the following error:

```js
{ name: 'Error',
      message:
       'Verification method "did:v1:test:nym:z6MktyAYL7sVcmPQPTbbMqrnGMNwp6zkvRvKREs94f81fA1K#z6MkgumSeJ8FGqFjXFPJSsT2EFCNYVvx5RXDQ6oBYDrmtiDb" not authorized by controller for proof purpose "assertionMethod".',
      stack:
       'Error: Verification method "did:v1:test:nym:z6MktyAYL7sVcmPQPTbbMqrnGMNwp6zkvRvKREs94f81fA1K#z6MkgumSeJ8FGqFjXFPJSsT2EFCNYVvx5RXDQ6oBYDrmtiDb" not authorized by controller for proof purpose "assertionMethod".\n    at CredentialIssuancePurpose.validate (/Users/guillaume/workspace/vc.transmute.world/node_modules/jsonld-signatures/lib/purposes/ControllerProofPurpose.js:91:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
```

**Comment by OR13** [comment]
I'm gonna hold on merging this until after plugfest.

**Comment by OR13** [comment]
remove credentials that are failing because of other vendors.

**Comment by gjgd** [comment]
ping @OR13 shall we merge this ?

**Pull request merged**
